### ISSUE TITLE
java.lang.LinkageError: ClassCastException: attempting to castbundleresource://64.fwk501244955/javax/ws/rs/client/ClientBuilder.class to bundleresource://829.fwk501244955:31/javax/ws/rs/client/ClientBuilder.class

### ISSUE THREAD

**Issue by kthoms** [jhipster/jhipster-ide#223]
The following error is reported to [Eclipse AERI](https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/incidents/5b881ac7e4b0ac09b9728a43):

```
Bundle: org.eclipse.ui 3.109.100.v20180426-0903
Message: Unhandled event loop exception
Exception:
java.lang.LinkageError: ClassCastException: attempting to castbundleresource://1008.fwk1680630881/javax/ws/rs/client/ClientBuilder.class to bundleresource://1057.fwk1680630881:31/javax/ws/rs/client/ClientBuilder.class
    at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:97)
    at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.init(JerseyDockerCmdExecFactory.java:226)
    at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:161)
    at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
    at ch.itemis.xdocker.lib.DockerExtensions.buildDockerClient(DockerExtensions.java:103)
    at ch.itemis.xdocker.lib.DockerExtensions.lambda$0(DockerExtensions.java:86)
    at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
    at ch.itemis.xdocker.lib.DockerExtensions.setupDocker(DockerExtensions.java:88)
    at ch.itemis.xdocker.lib.DockerExtensions.(DockerExtensions.java:79)
    at ch.itemis.xdocker.lib.DockerExtensions.newInstance(DockerExtensions.java:71)
    at ch.itemis.xdocker.ui.job.XdockerInfoJob.(XdockerInfoJob.java:55)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:488)
    at java.lang.Class.newInstance(Class.java:560)
    at ch.itemis.xdocker.ui.job.AbstractXdockerJob.create(AbstractXdockerJob.java:45)
    at ch.itemis.xdocker.ui.handler.XdockerDockerInfoHandler.execute(XdockerDockerInfoHandler.java:51)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:93)
    at jdk.internal.reflect.GeneratedMethodAccessor108.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
    at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

javax.ws.rs | 2.0.1.v201504171603
Xtext 2.13
Product org.eclipse.epp.package.jee.product_4.8.0.I20180611-0500
Java Runtime: 10.0.2+13-Ubuntu-1ubuntu0.18.04.1
Operating System: Linux, 4.15.0, x86_64, gtk

Similar incidents is reported multiple times.

**Comment by colameo** [comment]
Thanks for reporting, Karsten ;-)

**Comment by kthoms** [comment]
You're welcome :)

**Comment by colameo** [comment]
check underlying jars used in xdockercore.lib (duplicate and/or overlapping stuff)
