### ISSUE TITLE
NPE in PlantUMLRenderer

### ISSUE THREAD

**Issue by andreasmuelder** [jhipster/jhipster-ide#362]
A Nullpointer Exception Dialog pops up if other languages than the JDL are installed into the JHipster IDE. 
The renderer should guard if the language is a JDL Language.

```
java.lang.NullPointerException
	at io.github.jhipster.jdl.renderer.JdlToPlantUmlRenderer.init(JdlToPlantUmlRenderer.java:78)
	at io.github.jhipster.jdl.renderer.JdlToPlantUmlRenderer.render(JdlToPlantUmlRenderer.java:73)
	at io.github.jhipster.jdl.ui.modelviewer.JdlDiagramTextProvider.getDiagramText(JdlDiagramTextProvider.java:80)
	at ...
```

**Comment by colameo** [comment]
ok, thanks for reporting it.
