### ISSUE TITLE
Not compatible to Eclipse 23-09+

### ISSUE THREAD

**Issue by mbrandl87** [jhipster/jhipster-ide#402]
Hi,

I just unzipped a fresh eclipse 23-12 and installed JHipsteride from the marketplace.
Now framework event errors occour in the log and the extension doesn't even show up in the preferences, jdl files also can't be opened with the jdl editor.
I think tis already started in 23-06. 
is there any remidy action or would you have to update some bundle dependencies and publish a new version? Or did I miss some dependency? I noticed that it asks for lsp4j ~0.20, now eclipse got 0.21.1. 

Here is such a framework event error, just let me know if you need more info :)

Best 
Martin 
org.osgi.framework.BundleException: Could not resolve module: io.github.jhipster.jdl.ui [1002]
  Unresolved requirement: Require-Bundle: io.github.jhipster.jdl.ide
    -> Bundle-SymbolicName: io.github.jhipster.jdl.ide; bundle-version="2.7.0.202301072023"; singleton:="true"
       io.github.jhipster.jdl.ide [1000]
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.debug; bundle-version="[0.9.0,0.20.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j.debug; bundle-version="0.19.0.v20221118-0359"
              org.eclipse.lsp4j.debug [1026]
                Unresolved requirement: Import-Package: com.google.gson; version="[2.9.1,2.10.0)"
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="[0.9.0,0.20.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.19.0.v20221118-0359"
              org.eclipse.lsp4j [1025]
                Unresolved requirement: Import-Package: com.google.gson; version="[2.9.1,2.10.0)"
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.generator; bundle-version="[0.9.0,0.20.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j.generator; bundle-version="0.19.0.v20221118-0359"
              org.eclipse.lsp4j.generator [1027]
                Unresolved requirement: Import-Package: com.google.gson.annotations; version="[2.9.1,2.10.0)"
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc; bundle-version="[0.9.0,0.20.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.19.0.v20221118-0359"
              org.eclipse.lsp4j.jsonrpc [1028]
                Unresolved requirement: Import-Package: com.google.gson; version="[2.9.1,2.10.0)"
         Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc.debug; bundle-version="[0.9.0,0.20.0)"
           -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc.debug; bundle-version="0.19.0.v20221118-0359"
              org.eclipse.lsp4j.jsonrpc.debug [1029]
                Unresolved requirement: Import-Package: com.google.gson; version="[2.9.1,2.10.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by mbrandl87** [comment]
Hi there,

it seems also to be not compatible to 2024-03 but the marketplace site does state that it would. Is there a newer version than 2.7.0 or what am I doing wrong? :)

**Comment by colameo** [comment]
hi @mbrandl87,
thanks for notifying this mistake. The compatibility is set automatically by the eclipse marketplace platform administration ... However, I have now corrected it. Unfortunately, due to heavy workload in other projects, I didn't have time to update the project to the newest eclipse platform version - sorry.
